// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvmjnieozvtuzxyrfbth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52bWpuaWVvenZ0dXp4eXJmYnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDg3NDksImV4cCI6MjA2NDAyNDc0OX0.VAFFY7v7jw4D134x4PU1O8-rmlU619sTatc77KG-q-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);